blog/App/urls.py
from django.urls import path

from App import views
app_name = 'App'

urlpatterns = [
    # 首页
    path('index/',views.index,name='index'),

    # 框架
    # 右边标题栏
    path('header/', views.public_header, name='header'),
    # 左边导航栏
    path('left/', views.public_left, name='left'),

    # 主窗口，内容展示
    path('main/', views.public_main, name='main'),
    path('main/<int:cid>',views.public_main, name='main'),
    path('main/<int:cid>/<int:page>',views.public_main, name='main2'),


]

blog/ArticleManage/urls.py
from django.urls import path

from ArticleManage import views
app_name = 'ArticleManage'
urlpatterns = [
    path('delete/<int:aid>/<int:cid>/<int:page>/', views.delete_article, name='delete'),
    path('publish/<int:cid>/',views.publish_article, name='publish'),
    path('update/<int:cid>/<int:aid>/',views.update_article, name='update'),

]

blog/PictureChange/urls.py
from django.urls import path

from PictureChange import views

app_name ='PictureChange'
urlpatterns =[
    # 图片管理
    path('tpgl/', views.tpgl, name='tpgl'),
    # 系统管理
    path('syset/', views.syset, name='syset'),

]

blog/UserLogin/urls.py
from django.urls import path

from UserLogin import views

app_name = 'UserLogin'
urlpatterns = [
    # 首页
    path('index/',views.index,name='index'),
    # 首页头部
    path('header/', views.public_header, name='pubh'),

    # 首页左边分类栏
    path('publeft/',views.publeft,name='publft'),
    # 登陆页面
    path('login',views.login,name='login'),
    # 修改密码
    path('changepwd/',views.changepsw,name='changepsw'),
    # 图形验证码
    path('pageyz/', views.pageyz, name='pageyz'),

]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App.urls')),
    path('article/',include('ArticleManage.urls')),
    path('user/',include('UserLogin.urls'))
]

blog/App/models.py
from django.db import models

# Create your models here.
from django.db import models

# Create your models here.


class Article(models.Model):
    aid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100, blank=True, null=True)
    content = models.CharField(max_length=10000, blank=True, null=True)
    create_time = models.DateTimeField(blank=True, null=True)
    cid = models.ForeignKey('Category', models.DO_NOTHING, db_column='cid', blank=True, null=True)
    hits = models.IntegerField(blank=True, null=True)
    replies = models.IntegerField(blank=True, null=True)
    picture = models.CharField(max_length=300, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'article'

class Category(models.Model):
    cid = models.AutoField(primary_key=True)
    name = models.CharField(unique=True, max_length=100)
    num = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'category'


class Mark(models.Model):
    mid = models.AutoField(primary_key=True)
    content = models.CharField(max_length=1000, blank=True, null=True)
    create_time = models.DateTimeField(blank=True, null=True)
    uid = models.ForeignKey('User', models.DO_NOTHING, db_column='uid', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'mark'


class Tag(models.Model):
    tid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30, blank=True, null=True)
    aid = models.ForeignKey(Article, models.DO_NOTHING, db_column='aid', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'tag'


class User(models.Model):
    uid = models.AutoField(primary_key=True)
    username = models.CharField(unique=True, max_length=30)
    password = models.CharField(max_length=128)
    phone = models.CharField(max_length=11, blank=True, null=True)
    email = models.CharField(max_length=200, blank=True, null=True)
    portrait = models.CharField(max_length=300, blank=True, null=True)
    regtime = models.DateTimeField(blank=True, null=True)
    isforbid = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'user'

blog/ArticleManage/models.py
from django.db import models

# Create your models here.

blog/PictureChange/models.py
from django.db import models

# Create your models here.

blog/UserLogin/models.py
from django.db import models

# Create your models here.

blog/App/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, render_to_response

# Create your views here.
from App.models import Category, Article
from App.tools import BaiduPaginator


def index(request):
    return render(request,'index.html')

# 左边导航栏
def public_left(request):
    return render(request,"public_left.html")


def public_header(request):
    return render(request,'public_header.html')

# 文章管理
def public_main(request,cid=-1,page=1):
    categories = Category.objects.all()
    # 获取所有分类id
    postion = [cat.cid for cat in categories]
    if request.method == "POST":
        cid = int(request.POST.get('cid',-1))
        keyword = request.POST.get('keyword','')
        # 文章检索
        articles = Article.objects.filter(cid=cid,title__icontains=keyword)
    else:
        # 检索分类
        if cid < 0:
            first_category = categories.first() # 查询第一个分类
            cid = first_category.cid  # 第一个分类的cid

        # 文章检索
        articles = Article.objects.filter(cid=cid)

    pos = postion.index(cid)

    # 分页
    paginator = BaiduPaginator(articles,10)
    pager = paginator.page(page)
    pager.page_range = paginator.custom_range(10,page,5)

    return render(request,"wenzhang_xinwen.html",locals())

blog/ArticleManage/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse

from App.models import Article, Category


def delete_article(request,aid,cid=-1,page=1):
    """

    :param request:
    :param aid: 文章id
    :param cid: 类别id
    :param page: 当前页码
    :return:
    """
    arcticle = Article.objects.get(pk=aid)
    if arcticle:
        arcticle.delete()

    return redirect(reverse("App:main2", kwargs={'cid':cid,'page':page}))



def publish_article(request,cid=-1):
    if request.method == "POST":
        data = request.POST.dict()
        data.pop('csrfmiddlewaretoken')
        data.pop('photo')
        Article.add(**data)
        return redirect(reverse("App:main"))
    else:
        cid = cid if cid > 0 else Category.first_category().cid

        return render(request,'wenzhang_xinwen_fabu.html',locals())


def update_article(request,cid,aid):
    article = Article.objects.get(pk=aid)

    return render(request,'wenzhang_xinwen_info.html',locals())

blog/PictureChange/views.py
from django.http import HttpResponse
from django.shortcuts import render

# 图片管理
def tpgl(request):
    return render(request,'tupian_pc_index.html')

# 系统管理
def syset(request):
    return render(request,'xitong_set.html')

blog/UserLogin/views.py
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render
from UserLogin.func import pv

# 首页
def index(request):
    return render(request,'index.html')

# 首页头部分
def public_header(request):
    return render(request,'public_header.html')

# 首页左边分类栏
def publeft(request):
    return render(request,'public_left.html')

# 登陆
def login(request):
    return render(request,'loginb.html')
    # return render(request,'1.html')

# 修改密码
def changepsw(request):
    return render(request,'change_psw.html')

# 生成图片验证码
def pageyz(request):
    print("".center(50,"8"))
    result = pv.generate()
    # 把验证码字符串保存到session
    # request.session['code'] = pv.code
    # 创建响应对象
    res = HttpResponse(result,'image/png')
    # res.content_type = 'image/png'
    return res

blog/templates/change_psw.html
<!DOCTYPE html>
<html class=" js csstransforms3d"><head>
	<meta charset="utf-8">
	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>修改密码</title>
	<link rel="stylesheet" href="/static/css/base.css">
	<link rel="stylesheet" href="/static/css/page.css">
	<!--[if lte IE 8]>
	<link href="static/css/ie8.css" rel="stylesheet" type="text/css"/>
	<![endif]-->
	<script type="text/javascript" src=/static/js/jquery.min.js"></script>
	<script type="text/javascript" src=/static/js/main.js"></script>
	<script type="text/javascript" src=/static/js/modernizr.js"></script>
	<!--[if IE]>
	<script src="http://libs.useso.com/js/html5shiv/3.7/html5shiv.min.js"></script>
	<![endif]-->
</head>

<body style="background: #f6f5fa;">
	<!--content S-->
	<div class="super-content">
		<div class="superCtab">
			<div class="publishArt">
				<h4>修改密码</h4>
				<div class="pubMain">
					<h5 class="pubtitle">旧密码</h5>
					<div class="pub-txt-bar">
						<input type="password" class="shuruTxt shuruTxt2"><b class="error"></b>
						<div class="errorBox">您所输入的旧密码不正确，请重新输入！</div>
					</div>
					<h5 class="pubtitle">新密码<span>（数字、字母、符号组合，最少8个字符）</span></h5>
					<div class="pub-txt-bar">
						<input type="password" class="shuruTxt shuruTxt2"><b class="error"></b>
						<div class="errorBox">您所输入的旧密码不正确，请重新输入！</div>
					</div>
					<h5 class="pubtitle">确认密码</h5>
					<div class="pub-txt-bar">
						<input type="password" class="shuruTxt shuruTxt2"><b class="error"></b>
						<div class="errorBox">您所输入的旧密码不正确，请重新输入！</div>
					</div>
					<div class="pub-btn">
						<input type="button" id="" value="确定" class="saveBtn">
						<input type="button" id="" value="重置" class="resetBtn">
					</div>
				</div>
			</div>
		
		</div>
		<!--main-->
		
	</div>
	<!--content E-->
	


</body></html>

blog/templates/public_header.html
<!DOCTYPE html>
<html class=" js csstransforms3d"><head>
	<meta charset="utf-8">
	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>公共头部</title>
	<link rel="stylesheet" href="/static/css/base.css">
	<link rel="stylesheet" href="/static/css/page.css">
	<!--[if lte IE 8]>
	<link href="/static/css/ie8.css" rel="stylesheet" type="text/css"/>
	<![endif]-->
	<script type="text/javascript" src="/static/js/jquery.min.js"></script>
	<script type="text/javascript" src="/static/js/main.js"></script>
	<script type="text/javascript" src="/static/js/modernizr.js"></script>
	<!--[if IE]>
	<script src="http://libs.useso.com/js/html5shiv/3.7/html5shiv.min.js"></script>
	<![endif]-->
</head>

<body>
<div class="super-header clearfix">
	<h2>网站后台管理系统</h2>
	<div class="head-right">
		<i class="ico-user"></i>当前用户：
		<div class="userslideDown">
			<a href="javascript:;" class="superUser">Admin<i class="ico-tri"></i></a>
			<div class="slidedownBox">
				<ul>
					<li><a href="{% url 'UserLogin:changepsw' %}" target="Mainindex">修改密码</a></li>
					<li><a href="{% url 'UserLogin:login' %}" target="_parent">退出</a></li>
				</ul>
			</div>
		</div>
	</div>
</div>
<!--header-->


</body></html>

blog/templates/wenzhang_xinwen.html
<!DOCTYPE html>
<html class=" js csstransforms3d"><head>
	<meta charset="utf-8">
	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>文章发布</title>
	<link rel="stylesheet" href="/static/css/base.css">
	<link rel="stylesheet" href="/static/css/page.css">

	<script type="text/javascript" src="/static/js/jquery.min.js"></script>
	<script type="text/javascript" src="/static/js/main.js"></script>
	<script type="text/javascript" src="/static/js/modernizr.js"></script>

</head>

<body style="background: #f6f5fa;">

	<!--content S-->
	<div class="super-content RightMain" id="RightMain">
		
		<!--header-->
		<div class="superCtab">
			<div class="ctab-title clearfix"><h3>文章发布</h3><a href="javascript:;" class="sp-column"><i class="ico-mng"></i>栏目管理</a></div>
			
			<div class="ctab-Main">
				<div class="ctab-Main-title">
					<ul class="clearfix">
{#						<li class="cur"><a href="wenzhang_xinwen.html">新闻动态</a></li>#}
						{% for cateory in categories %}
                           <li><a href="{% url 'App:main' cid=cateory.cid  %}">{{ cateory.name }}</a></li>
                        {% endfor %}
                      <script>
                          $(".ctab-Main-title li").eq({{ pos }}).addClass('cur')

                      </script>
					</ul>
				</div>

				<div class="ctab-Mian-cont">
					<div class="Mian-cont-btn clearfix">
						<div class="operateBtn">
							<a href="{% url 'ArticleManage:publish' cid=cid %}" class="greenbtn publish">发布文章</a>
{#							<a href="javascript:;" class="greenbtn add sp-add">添加分类</a>#}
{#							<a href="javascript:;" class="greenbtn add sp-photo" id="preview">栏目图片</a>#}
{#							<a href="javascript:;" class="modify sp-modify" id="sp-modify">修改</a>#}
						</div>
						<div class="searchBar">
                            <form action="{% url 'App:main' cid=cid %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="cid" value="{{ cid }}">
                                <input type="text" name="keyword" value="" class="form-control srhTxt" placeholder="输入标题关键字搜索">
                                <input type="submit" class="srhBtn" value="">
                            </form>
						</div>
					</div>
{#					<div class="super-label clearfix">#}
{#						<a href="#">行业新闻<em style="display: none;"></em></a><a href="#">保险常识<em style="display: none;"></em></a>#}
{#					</div>#}
{#					#}
					<div class="Mian-cont-wrap">
						<div class="defaultTab-T">
							<table border="0" cellspacing="0" cellpadding="0" class="defaultTable">
								<tbody><tr><th class="t_1">文章ID</th><th class="t_2">文章标题</th><th class="t_3">发布时间</th><th class="t_4">操作</th></tr>
							</tbody></table>
						</div>
						<table border="0" cellspacing="0" cellpadding="0" class="defaultTable defaultTable2">
							<tbody>
							{% for article  in pager.object_list %}
							<tr>
								<td class="t_1">{{ article.aid }}</td>
								<td class="t_2"><a href="#">{{ article.title }}</a></td>
								<td class="t_3">{{ article.create_time }}</td>
								<td class="t_4"><div class="btn"><a class="Top">置顶</a>
                                    <a href="{% url 'ArticleManage:update' cid=cid aid=article.aid %}" class="modify">修改</a>
                                    <a href="{% url 'ArticleManage:delete' aid=article.aid cid=cid page=page %}" class="delete">删除</a></div></td>
							</tr>
                            {% endfor %}


						</tbody></table>
						<!--pages S-->
						<div class="pageSelect">
							<span>共 <b>{{ paginator.count }}</b> 条 每页 <b>{{ paginator.per_page }} </b>条   {{pager.number}}/{{ paginator.num_pages }}</span>
							<div class="pageWrap">
								<a class="pagePre"><i class="ico-pre">&nbsp;</i></a>
                                {% for current in pager.page_range %}
                                    {% if pager.number == current %}
                                        <a href="{% url 'App:main2' cid=cid page=current %}" class="pagenumb cur">{{ current }}</a>
                                    {% else %}
                                        <a href="{% url 'App:main2' cid=cid page=current %}" class="pagenumb">{{ current }}</a>
                                    {% endif %}
                                {% endfor %}
								<a href="#" class="pagenext"><i class="ico-next">&nbsp;</i></a>
							</div>
						</div>
						<!--pages E-->
					</div>

				</div>
			</div>
		</div>
		<!--main-->

	</div>
	<!--content E-->

	<div class="layuiBg"></div><!--公共遮罩-->
	<!--点击修改弹出层-->
	<div class="imgXgbox layuiBox">
		<div class="layer-title clearfix"><h2>修改栏目图片</h2><span class="layerClose"></span></div>
		<div class="layer-content">
			<div class="XgfileImg"><img src="/static/images/bg_img_sc.jpg"><input id="fileImage" class="fileImageSlect" type="file" size="30" name="fileselect[]"></div>
			<p class="onclktip">（点击图片可重新上传）</p>
			<div class="Xgimglink clearfix"><span>图片链接：</span><input type="text" value=""></div>
			<div class="XgBtn"><input type="button" value="保存" class="saveBtn"></div>
		</div>
	</div>

	<!--栏目管理-->
	<div class="Columnbox layuiBox">
		<div class="layer-title clearfix"><h2>栏目管理</h2><span class="layerClose"></span></div>
		<div class="layer-content">
			<ul class="colu-title clearfix">
				<li class="li-1">栏目名称</li><li class="li-2">英文名称</li><li class="li-3">操作</li><li class="li-4">同步开关</li>
			</ul>
			<div class="colu-list">
				<ul class="colu-cont clearfix active">
					<li class="li-1"><i class="ico"></i>新闻动态</li><li class="li-2">life</li><li class="li-3"><a href="javascript:;" class="colu-xg" data-id="xg1">修改</a></li><li class="li-4"><input type="checkbox" id="checkbox_d1" class="chk_4"><label for="checkbox_d1"></label></li>
				</ul>
				<div class="colunext" style="display: block;">
					<ul class="colu-next clearfix">
						<li class="li-1"><i class="ico"></i>行业新闻</li><li class="li-2"></li><li class="li-3"><a href="javascript:;" class="colu-xg" data-id="xg2">修改</a></li>
					</ul>
					<ul class="colu-next clearfix">
						<li class="li-1"><i class="ico"></i>行业新闻</li><li class="li-2"></li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li>
					</ul>
				</div>
			</div><!--新闻动态-->
			<div class="colu-list">
				<ul class="colu-cont clearfix">
					<li class="li-1"><i class="ico"></i>品尚生活</li><li class="li-2">news</li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li><li class="li-4"><input type="checkbox" id="checkbox_d2" class="chk_4"><label for="checkbox_d2"></label></li>
				</ul>
				<div class="colunext">
					<ul class="colu-next clearfix">
						<li class="li-1"><i class="ico"></i>行业新闻</li><li class="li-2"></li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li>
					</ul>
					<ul class="colu-next clearfix">
						<li class="li-1"><i class="ico"></i>行业新闻</li><li class="li-2"></li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li>
					</ul>
				</div>
			</div><!--品尚生活-->
			<div class="colu-list">
				<ul class="colu-cont clearfix">
					<li class="li-1"><i class="ico"></i>卓越联盟</li><li class="li-2">allance</li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li><li class="li-4"><input type="checkbox" id="checkbox_d3" class="chk_4"><label for="checkbox_d3"></label></li>
				</ul>
				<div class="colunext">
					<ul class="colu-next clearfix">
						<li class="li-1"><i class="ico"></i>行业新闻</li><li class="li-2"></li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li>
					</ul>
					<ul class="colu-next clearfix">
						<li class="li-1"><i class="ico"></i>行业新闻</li><li class="li-2"></li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li>
					</ul>
				</div>
			</div><!--卓越联盟-->
			<div class="colu-list">
				<ul class="colu-cont clearfix">
					<li class="li-1"><i class="ico"></i>招贤纳士</li><li class="li-2">managers</li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li><li class="li-4"><input type="checkbox" id="checkbox_d4" class="chk_4" checked=""><label for="checkbox_d4"></label></li>
				</ul>
				<div class="colunext">
					<ul class="colu-next clearfix">
						<li class="li-1"><i class="ico"></i>行业新闻</li><li class="li-2"></li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li>
					</ul>
					<ul class="colu-next clearfix">
						<li class="li-1"><i class="ico"></i>行业新闻</li><li class="li-2"></li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li>
					</ul>
				</div>
			</div><!--招贤纳士-->
			<div class="colu-list">
				<ul class="colu-cont clearfix">
					<li class="li-1"><i class="ico"></i>客户见证</li><li class="li-2">witness</li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li><li class="li-4"><input type="checkbox" id="checkbox_d5" class="chk_4" checked=""><label for="checkbox_d5"></label></li>
				</ul>
				<div class="colunext">
					<ul class="colu-next clearfix">
						<li class="li-1"><i class="ico"></i>行业新闻</li><li class="li-2"></li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li>
					</ul>
					<ul class="colu-next clearfix">
						<li class="li-1"><i class="ico"></i>行业新闻</li><li class="li-2"></li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li>
					</ul>
				</div>
			</div><!--客户见证-->
			<div class="colu-list">
				<ul class="colu-cont clearfix">
					<li class="li-1"><i class="ico"></i>热门产品</li><li class="li-2">product</li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li><li class="li-4"><input type="checkbox" id="checkbox_d6" class="chk_4" checked=""><label for="checkbox_d6"></label></li>
				</ul>
				<div class="colunext">
					<ul class="colu-next clearfix">
						<li class="li-1"><i class="ico"></i>行业新闻</li><li class="li-2"></li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li>
					</ul>
					<ul class="colu-next clearfix">
						<li class="li-1"><i class="ico"></i>行业新闻</li><li class="li-2"></li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li>
					</ul>
				</div>
			</div><!--热门产品-->
			<div class="colu-list">
				<ul class="clearfix colu-cont-no">
					<li class="li-1"><i class="ico"></i>关于我们</li><li class="li-2">about</li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li><li class="li-4"></li>
				</ul>
			</div><!--关于我们-->
			<div class="colu-list">
				<ul class="clearfix colu-cont-no">
					<li class="li-1"><i class="ico"></i>联系方式</li><li class="li-2">contact</li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li><li class="li-4"></li>
				</ul>
			</div><!--联系方式-->
			
		</div>
	</div>
	<!--栏目管理－修改-->
	<div class="ColumnXgbox layuiBox">
		<div class="layer-title clearfix"><h2>添加分类</h2><span class="layerClose"></span></div>
		<div class="layer-content">
			<div class="aFllink clearfix"><span>修改名称：</span><input type="text" value=""></div>
			<div class="aFllink clearfix"><span>英文名称：</span><input type="text" value=""></div>
			<div class="aFlBtn"><input type="button" value="保存" class="saveBtn"></div>
		</div>
	</div>



<script type="text/javascript" src="/static/js/zxxFile.js"></script>
<script>
var params = {
	fileInput: $("#fileImage").get(0),
	upButton: $("#fileSubmit").get(0),
	url: $("#uploadForm").attr("action"),
	filter: function(files) {
		var arrFiles = [];
		for (var i = 0, file; file = files[i]; i++) {
			if (file.type.indexOf("image") == 0) {
				if (file.size >= 512000) {
					alert('您这张"'+ file.name +'"图片大小过大，应小于500k');	
				} else {
					arrFiles.push(file);	
				}			
			} else {
				alert('文件"' + file.name + '"不是图片。');	
			}
		}
		return arrFiles;
	},
	onSelect: function(files) {
		var html = '', i = 0;
		$("#preview").html('<div class="upload_loading"></div>');
		var funAppendImage = function() {
			file = files[i];
			if (file) {
				var reader = new FileReader()
				reader.onload = function(e) {
					$('.XgfileImg img').attr('src', e.target.result);
					$('.sp-photo').addClass('cur');
					html = html + '<div id="uploadList_'+ i +'" class="upload_append_list"><p><span>' + file.name + '</span>'+ 
						'<a href="javascript:" class="upload_delete" title="删除" data-index="'+ i +'">删除</a>' +
					'</div>';
					
					i++;
					funAppendImage();
				}
				reader.readAsDataURL(file);
			} else {
				$("#preview").html(html);
				if (html) {
					//删除方法
					$(".upload_delete").click(function() {
						ZXXFILE.funDeleteFile(files[parseInt($(this).attr("data-index"))]);
						$('.sp-photo').removeClass('cur').html('栏目图片');
						return false;	
					});
					//提交按钮显示
					$("#fileSubmit").show();	
				} else {
					//提交按钮隐藏
					$("#fileSubmit").hide();	
				}
			}
		};
		funAppendImage();		
	},
	onDelete: function(file) {
		$("#uploadList_" + file.index).fadeOut();
	},
	onDragOver: function() {
		$(this).addClass("upload_drag_hover");
	},
	onDragLeave: function() {
		$(this).removeClass("upload_drag_hover");
	},
	onProgress: function(file, loaded, total) {
		var eleProgress = $("#uploadProgress_" + file.index), percent = (loaded / total * 100).toFixed(2) + '%';
		eleProgress.show().html(percent);
	},
	onSuccess: function(file, response) {
		$("#uploadInf").append("<p>上传成功，图片地址是：" + response + "</p>");
	},
	onFailure: function(file) {
		$("#uploadInf").append("<p>图片" + file.name + "上传失败！</p>");	
		$("#uploadImage_" + file.index).css("opacity", 0.2);
	},
	onComplete: function() {
		//提交按钮隐藏
		$("#fileSubmit").hide();
		//file控件value置空
		$("#fileImage").val("");
		$("#uploadInf").append("<p>当前图片全部上传完毕，可继续添加上传。</p>");
	}
};
ZXXFILE = $.extend(ZXXFILE, params);
ZXXFILE.init();

</script>

</body></html>